<a href="https://colab.research.google.com/github/gustavogrds/TIC/blob/master/Arvores_de_Decisao_Classificadores_comparados_gabarito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="Universidade Presbiteriana Mackenzie">
</head>

<img src="http://meusite.mackenzie.br/rogerio/mackenzie_logo/UPM.2_horizontal_vermelho.jpg" width=300, align="right"></a>
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

<h1 align=left><font size = 6, style="color:rgb(200,0,0)">Lab</font></h1>
<hr>

 # **Árvores de Decisão e Modelos Supervisionados**
 ## Instruções

1. Empregue para este Laboratório o **material de Teoria**.

1. **Responda as questões** à medida que você realiza o Lab.

2. Execute este Lab no **Colab Google**.

# Caso: **Renda baseada no Censo Americano**

Descrição dos metadados pode ser encontradas na página oficial do dataset:

https://archive.ics.uci.edu/dataset/2/adult

Preveja se a renda excede US$ 50 mil/ano com base nos dados do censo. Também conhecido como conjunto de dados "Renda do Censo".


Os dados estão na URL: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data




# Exercício. Acesse e Explore os dados

1. Qual o atributo **classe**?
1. Quantos registros de cada **classe**?
1. Todos os dados são numéricos? (por quê?)
1. Os dados encontram-se na mesma escala?
1. Qual o tamanho dos dados? (linhas e atributos)
1. Existem valores nulos?


In [ ]:
# imports

import pandas                  as pd
import numpy                   as np
import matplotlib.pyplot       as plt
import warnings
import os
import seaborn as sns
warnings.filterwarnings("ignore")

In [ ]:
# Adult dataset
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None)
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
df

age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

Responda as perguntas acima de 1 a 6 nas células abaixo:

In [ ]:
# Seu código aqui...

In [ ]:
# Seu código aqui ...



# Exercício

Aqui verificamos se existem valores ausentes nos dados. Valores ausentes trazem em geral problemas (por quê?) e precisam ser tratados antes de empregarmos modelos. Assim como valores categóricos para alguns classificadores.

df.isnull().sum()

# Exercício. Defina as entradas `X` e saída `y` modelo

Lembre-se, em um modelo de classificação $X$ são as variáveis preditoras (*independentes*) e $y$ sua variável objetivo (*dependente*). Comece fazendo o hot encode das variáveis categóricas através do comando pd.get_dummies

In [ ]:
df = pd.get_dummies(df, columns=['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country'])

In [ ]:
df

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0       39   77516             13          2174             0              40   
1       50   83311             13             0             0              13   
2       38  215646              9             0             0              40   
3       53  234721              7             0             0              40   
4       28  338409             13             0             0              40   
...    ...     ...            ...           ...           ...             ...   
32556   27  257302             12             0             0              38   
32557   40  154374              9             0             0              40   
32558   58  151910              9             0             0              40   
32559   22  201490              9             0             0              20   
32560   52  287927              9         15024             0              40   

       income  workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0       <=50K             0                       0                     0   
1       <=50K             0                       0                     0   
2       <=50K             0                       0                     0   
3       <=50K             0                       0                     0   
4       <=50K             0                       0                     0   
...       ...           ...                     ...                   ...   
32556   <=50K             0                       0                     0   
32557    >50K             0                       0                     0   
32558   <=50K             0                       0                     0   
32559   <=50K             0                       0                     0   
32560    >50K             0                       0                     0   

       ...  native-country_ Portugal  native-country_ Puerto-Rico  \
0      ...                         0                            0   
1      ...                         0                            0   
2      ...                         0                            0   
3      ...                         0                            0   
4      ...                         0                            0   
...    ...                       ...                          ...   
32556  ...                         0                            0   
32557  ...                         0                            0   
32558  ...                         0                            0   
32559  ...                         0                            0   
32560  ...                         0                            0   

       native-country_ Scotland  native-country_ South  \
0                             0                      0   
1                             0                      0   
2                             0                      0   
3                             0                      0   
4                             0                      0   
...                         ...                    ...   
32556                         0                      0   
32557                         0                      0   
32558                         0                      0   
32559                         0                      0   
32560                         0                      0   

       native-country_ Taiwan  native-country_ Thailand  \
0                           0                         0   
1                           0                         0   
2                           0                         0   
3                           0                         0   
4                           0                         0   
...                       ...                       ...   
32556                       0                         0   
32557                       0                         0   
32558                       0                       

In [ ]:
# Seu código

X = df.drop('income', axis=1)
y = df['income']

# Exercício. Separe os Conjuntos de Treinamento `X_train`, `y_train` e Test `X_test`, `y_test`


In [ ]:
# Seu código
from sklearn.model_selection import train_test_split
seed = 1984

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=seed)

Qual a dimensão dos conjuntos `X_train, X_test, y_train, y_test`?

In [ ]:
# Seu código
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(22792, 108) (9769, 108) (22792,) (9769,)


Exiba os primeiros registros de `X_train`. Qual o primeiro registro que aparece?

In [ ]:
# Seu código
X_train.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
17627   26  279833             13             0          2258              45   
7599    43  188808             14             0             0              45   
7639    19   91928             10             0             0              35   
10537   20  197752             10             0             0              40   
100     76  124191             14             0             0              40   

       workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
17627             0                       0                     0   
7599              0                       0                     0   
7639              0                       0                     0   
10537             0                       0                     0   
100               0                       0                     0   

       workclass_ Never-worked  ...  native-country_ Portugal  \
17627                        0  ...                         0   
7599                         0  ...                         0   
7639                         0  ...                         0   
10537                        0  ...                         0   
100                          0  ...                         0   

       native-country_ Puerto-Rico  native-country_ Scotland  \
17627                            0                         0   
7599                             0                         0   
7639                             0                         0   
10537                            0                         0   
100                              0                         0   

       native-country_ South  native-country_ Taiwan  \
17627                      0                       0   
7599                       0                       0   
7639                       0                       0   
10537                      0                       0   
100                        0                       0   

       native-country_ Thailand  native-country_ Trinadad&Tobago  \
17627                         0                                0   
7599                          0                                0   
7639                          0                                0   
10537                         0                                0   
100                           0                                0   

       native-country_ United-States  native-country_ Vietnam  \
17627                              1                        0   
7599                               1                        0   
7639                               1                        0   
10537                              1                        0   
100                                1                        0   

       native-country_ Yugoslavia  
17627                           0  
7599                            0  
7639                            0  
10537                           0  
100                             0  

[5 rows x 108 columns]

# Exercício. Declare o modelo e seus parâmetros `clf = model`

Declare um modelo de Árvore de decisão com o critério `gini` e o `seed` = 1984. use max_depth=None.

In [ ]:
# Seu código
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='gini',
                              max_depth=None,
                              random_state=seed)

# Exercício. Treine o modelo `clf.train(X_train, y_train)` e aplique ao conjunto de Teste `clf.pred(X_test)`


In [ ]:
# Seu código
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

Qual a previsão para os 3 primeiros casos?

In [ ]:
# Seu código
y_pred

array([' >50K', ' >50K', ' >50K', ..., ' <=50K', ' >50K', ' <=50K'],
      dtype=object)

Quantos casos foram classificados como '>50K'?


In [ ]:
# Seu código
sum(y_pred == ' >50K')

2394

# Exercício. Verifique os resultados, avaliando a matriz de confusão, o score de acurácia e o classification report. O que é possível concluir sobre o modelo?

In [ ]:
# Seu código
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[6518  899]
 [ 857 1495]]


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.820247722387143


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       <=50K       0.88      0.88      0.88      7417
        >50K       0.62      0.64      0.63      2352

    accuracy                           0.82      9769
   macro avg       0.75      0.76      0.76      9769
weighted avg       0.82      0.82      0.82      9769



# Exercício. Crie um novo modelo `clf2` a partir do modelo anterior, alterando o método de seleção dos nós para `entropy` e a profundidade máxima da árvore para 16.

O resultado é melhor ou pior que o modelo anterior?

In [ ]:
# Seu código para o modelo...
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(criterion='entropy',
                              max_depth=16,
                              random_state=seed)

clf2.fit(X_train, y_train)

y_pred = clf2.predict(X_test)

In [ ]:
# Seu código para avaliação dos resultados...
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

print(classification_report(y_test,y_pred))

[[6817  600]
 [ 868 1484]]
0.8497287337496161
              precision    recall  f1-score   support

       <=50K       0.89      0.92      0.90      7417
        >50K       0.71      0.63      0.67      2352

    accuracy                           0.85      9769
   macro avg       0.80      0.78      0.79      9769
weighted avg       0.84      0.85      0.85      9769



Na sua conclusão o modelo 2 é melhor que o primeiro?

# Exercício. Crie um novo modelo `clf3` do tipo k-vizinhos k=5 mais próximos

O resultado é melhor ou pior que o modelo anterior?

In [ ]:
# Seu código

from sklearn import neighbors
n_neighbors = 5
clf3 = neighbors.KNeighborsClassifier(n_neighbors)

clf3.fit(X_train, y_train)
y_pred = clf3.predict(X_test)


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

print(classification_report(y_test,y_pred))

[[6834  583]
 [1629  723]]
              precision    recall  f1-score   support

       <=50K       0.81      0.92      0.86      7417
        >50K       0.55      0.31      0.40      2352

    accuracy                           0.77      9769
   macro avg       0.68      0.61      0.63      9769
weighted avg       0.75      0.77      0.75      9769



Exercício: Crie um modelo de regressão logística para esses dados e compare a classificação:

In [ ]:
>>> from sklearn.linear_model import LogisticRegression

clf4 = LogisticRegression()

clf4.fit(X_train, y_train)
y_pred = clf4.predict(X_test)


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

print(classification_report(y_test,y_pred))

[[7194  223]
 [1745  607]]
              precision    recall  f1-score   support

       <=50K       0.80      0.97      0.88      7417
        >50K       0.73      0.26      0.38      2352

    accuracy                           0.80      9769
   macro avg       0.77      0.61      0.63      9769
weighted avg       0.79      0.80      0.76      9769

